[package]
name = "stock_predictor"
version = "0.1.0"
edition = "2021"

[dependencies]
# General
time = "0.3.22"

# Data
regex = "1.8.4"
yahoo_finance_api = { version = "2.0.0", features = ["blocking"] }

# Model
ndarray = "0.15.6"

linfa = "0.6.1"
linfa-linear = "0.6.1"
